//! Protobuf contract types for autocipher, generated by [`prost`] from
//! `proto/autocipher.v1.proto` — the single source of truth shared with the
//! Dart side (`protoc --dart_out` into `dart/lib/src/gen`, committed).
//!
//! The generated types are pure payloads; the C ABI framing of the bridge
//! (per-op symbols, opaque handles, error codes) lives in the Rust bridge and
//! is mirrored by the generated C header / Dart bindings instead.

pub mod v1 {
    #![allow(clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/autocipher.v1.rs"));
}

#[cfg(test)]
mod tests {
    use super::v1 as proto;
    use prost::Message;

    fn to_hex(bytes: &[u8]) -> String {
        let mut s = String::with_capacity(bytes.len() * 2);
        for b in bytes {
            s.push_str(&format!("{b:02x}"));
        }
        s
    }

    /// The `AddPaths` batch exercising repeated items and both path styles
    /// (Windows and POSIX) — the golden vector shared with the Dart side.
    fn golden_add_paths() -> proto::AddPaths {
        proto::AddPaths {
            items: vec![
                proto::PathItem {
                    src: "C:\\Users\\me\\DSC0001.jpg".to_string(),
                    stored_name: "photos/DSC0001.jpg".to_string(),
                },
                proto::PathItem {
                    src: "/home/me/doc.txt".to_string(),
                    stored_name: "doc.txt".to_string(),
                },
            ],
        }
    }

    fn golden_file_list() -> proto::FileInfoList {
        proto::FileInfoList {
            files: vec![
                proto::FileInfo {
                    name: "photos/DSC0001.jpg".to_string(),
                    size: 1_048_576,
                },
                proto::FileInfo {
                    name: "doc.txt".to_string(),
                    size: 42,
                },
            ],
        }
    }

    fn golden_kdf() -> proto::KdfParams {
        proto::KdfParams {
            memory: proto::kdf_params::Memory::M256 as i32,
            t: 4,
            p: 4,
        }
    }

    /// Golden byte vectors, shared with the Dart golden test
    /// (`dart/test/golden_test.dart`). Both languages must encode identical
    /// messages to identical bytes; the literals below are the locked parity
    /// check.
    const GOLDEN_ADD_PATHS_HEX: &str = "0a2d0a17433a5c55736572735c6d655c445343303030312e6a7067121270686f746f732f445343303030312e6a70670a1b0a102f686f6d652f6d652f646f632e7478741207646f632e747874";
    const GOLDEN_FILE_LIST_HEX: &str = "0a180a1270686f746f732f445343303030312e6a7067108080400a0b0a07646f632e747874102a";
    const GOLDEN_KDF_HEX: &str = "080110041804";

    #[test]
    fn add_paths_matches_golden_bytes() {
        assert_eq!(
            to_hex(&golden_add_paths().encode_to_vec()),
            GOLDEN_ADD_PATHS_HEX
        );
    }

    #[test]
    fn file_list_matches_golden_bytes() {
        assert_eq!(
            to_hex(&golden_file_list().encode_to_vec()),
            GOLDEN_FILE_LIST_HEX
        );
    }

    #[test]
    fn kdf_matches_golden_bytes() {
        assert_eq!(to_hex(&golden_kdf().encode_to_vec()), GOLDEN_KDF_HEX);
    }

    /// Round-trip: encode -> decode -> re-encode must reproduce the exact bytes.
    #[test]
    fn add_paths_roundtrip_is_stable() {
        let bytes = golden_add_paths().encode_to_vec();
        let decoded = proto::AddPaths::decode(bytes.as_slice()).unwrap();
        assert_eq!(decoded.encode_to_vec(), bytes);
        assert_eq!(decoded.items.len(), 2);
        assert_eq!(decoded.items[0].stored_name, "photos/DSC0001.jpg");
    }

    #[test]
    fn file_list_roundtrip_is_stable() {
        let bytes = golden_file_list().encode_to_vec();
        let decoded = proto::FileInfoList::decode(bytes.as_slice()).unwrap();
        assert_eq!(decoded.encode_to_vec(), bytes);
        assert_eq!(decoded.files[1].size, 42);
    }

    /// Error-code mapping sanity: every `ErrorCode` variant keeps its stable,
    /// ABI-facing number. (SESSION_NOT_FOUND was dropped with the envelope;
    /// the numbers 0–9 are load-bearing across the C ABI.)
    #[test]
    fn error_code_values_are_stable() {
        assert_eq!(proto::ErrorCode::Unspecified as i32, 0);
        assert_eq!(proto::ErrorCode::WrongPassword as i32, 1);
        assert_eq!(proto::ErrorCode::NotFound as i32, 2);
        assert_eq!(proto::ErrorCode::AlreadyExists as i32, 3);
        assert_eq!(proto::ErrorCode::Crypto as i32, 4);
        assert_eq!(proto::ErrorCode::Io as i32, 5);
        assert_eq!(proto::ErrorCode::Kdf as i32, 6);
        assert_eq!(proto::ErrorCode::MetadataTooLarge as i32, 7);
        assert_eq!(proto::ErrorCode::InvalidArgument as i32, 8);
        assert_eq!(proto::ErrorCode::Internal as i32, 9);
    }
}