// Placeholder for the Swift wrapper around the autocipher C ABI.
//
// The typed `Vault` API is generated by the `#[ac_fn]` codegen (the Swift
// renderer still pending). Raw surface: the symbols in
// `include/autocipher_capi.h`, which is imported by this module's umbrella
// header so Swift Package Manager builds it against the checked-in header.
//
// Load order mirrors the Dart/Java sides: `AUTOCIPHER_FFI_LIB` override,
// bundled `libautocipher_ffi.dylib`, then the system search path.
public enum Autocipher {
    /// Version triple reported by the native engine on this process.
    /// Returns (0,0,0) if the library is not yet loaded.
    public static func version() -> (major: Int32, minor: Int32, patch: Int32) {
        var major: Int32 = 0
        var minor: Int32 = 0
        var patch: Int32 = 0
        ac_version(&major, &minor, &patch)
        return (major, minor, patch)
    }
}